development:
  adapter: sqlite3
  encoding: unicode
  database: db/todo_development.sqlite3
  host: localhost
  pool: 5
  username: <%= ENV["DEV_DATABASE_USERNAME"] %>
  password: <%= ENV["DEV_DATABASE_PASSWORD"] %>

test:
  adapter: sqlite3
  encoding: unicode
  database: db/todo_test.sqlite3
  host: localhost
  template: template0
  pool: 5
  username: <%= ENV["TEST_DATABASE_USERNAME"] %>
  password: <%= ENV["TEST_DATABASE_PASSWORD"] %>

production:
  adapter: sqlite3
  encoding: unicode
  database: db/todo_production.sqlite3
  pool: 5
  username:
  password:
