development:
  adapter: postgresql
  host: localhost
  port: 5432
  encoding: unicode
  database: todo_development
  pool: 5
  username: postgres
  password: SpragueAshwell87!

test:
  adapter: postgresql
  host: localhost
  port: 5432
  encoding: unicode
  database: todo_test
  pool: 5
  username: postgres  
  password: SpragueAshwell87!

production:
  adapter: postgresql
  encoding: unicode
  database: todo_production
  pool: 5
  username: 
  password:
